{% set name = "pygnome" %}
{% set version = "1.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-ORR-ERD/PyGnome/archive/v{{ version }}.tar.gz
  sha256: 77e07b73fd39ab5c0f913b572db90ee6f59bc335712424cfa3923806be14227d

build:
  skip: true  # [py<39 or py>312]
  missing_dso_whitelist:
    - "*/lib_gnome.dll"         # [win]
    - "*/point_in_polygon.dll"  # [win]
  number: 0
  script:
    - export CMAKE_GENERATOR=Ninja  # [unix]
    - cd py_gnome && {{ PYTHON }} -m pip install ./ -vv

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - netCDF4                             # [build_platform != target_platform]
    - scikit-build-core                   # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - libcxx-devel <19  # [osx]
    - ninja
    - cmake
    - make
  host:
    - python
    - pip
    - numpy
    - cython
    - scikit-build-core
    - blosc
    - bzip2
    - curl
    - hdf4
    - hdf5
    - libcurl
    - libnetcdf
    - libaec
    - libxml2
    - libzip
    - openssl
    - zlib
    - zstd
  run:
    - python
    - awesome-slugify
    - progressbar
    - numpy >=1.24
    - scipy
    - colander <2
    - gsw
    - netCDF4
    - trimesh
    - geojson
    - geopandas
    - mapbox_earcut
    - pyogrio
    - pyproj
    - shapely >=2.0.6
    - gridded >=0.6.10
    - pynucos >=3.3.0
    - cell_tree2d
    - py_gd >=2.3
    - adios_db >=1.2.4
test:
  imports:
    - gnome
  commands:
    - python -c "import gnome; assert gnome.__version__ == '{{ version }}'"

about:
  home: https://github.com/NOAA-ORR-ERD/PyGnome
  license: Unlicense
  license_file: LICENSE.txt
  summary: |
    PyGNOME is flexible particle-tracking framework adapted to oil spill modeling.

  description: |
    GNOME (General NOAA Operational Modeling Environment) is flexible particle
    tracking framework developed by the National Oceanic and Atmospheric
    Administration (NOAA), Office of Response and Restoration (ORR),
    Emergency Response Division. It is designed to support oil and other
    hazardous material spills in the coastal environment, and is also a
    full featured, flexible particle tracking system, that can be used for
    other oceanographic transport applications, such as fish larvae,
    marine debris, etc.

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - jay-hennen
